### ISSUE TITLE
Certain changes not added to final build

### ISSUE THREAD

**Issue by Thathip** [MCPHackers/RetroMCP-Java#102]
When I add changes to Minecraft.java, GuiMainMenu.java, GuiMultiplayer.java, GuiInGame.java, and PanelCrashReport.java, only the changes from Minecraft.java and GuiInGame.java got added to the jar

version : a1.0.16_02

Help please?

(what i was trying to do was change the version string of the build)

**Comment by mudkipdev** [comment]
Which Java version are you using?

**Comment by Thathip** [comment]
Java 1.8,16, and 17

**Comment by Thathip** [comment]
I have no idea, how am i supposed to know?

**Comment by Thathip** [comment]
> > Java 1.8,16, and 17
> 
> Which one are you launching RetroMCP with?

How do I find it? I dont know?

**Comment by Thathip** [comment]
> > > Java 1.8,16, and 17
> > 
> > Which one are you launching RetroMCP with?
> 
> How do I find it? I dont know?

I found it, 17.0.8

**Comment by Thathip** [comment]
And when I revert the only classes that would apply to the client back to their original, the other code still wouldn't apply. Got any solutions?

**Comment by Thathip** [comment]
I tried with just Java 1.8 installed and it still doesn't work.

**Comment by PhoenixVX** [comment]
Is this still an issue?

**Comment by Thathip** [comment]
sorry for not responding but yes for me

**Comment by Thathip** [comment]
> Is this still an issue?

sorry for not responding but yea, even tried the 1.0.1 compiled from source

**Comment by Thathip** [comment]
and this might be a problem but did i not mention that i use intellij?

**Comment by PhoenixVX** [comment]
Intellij support is currently broken in that case. Changes won't be applied in the environment unless you enable "Use Eclipse dependency format" in project/module settings.
