### ISSUE TITLE
(b1.7.3) Font is not loaded

### ISSUE THREAD

**Issue by Nyvyme** [MCPHackers/RetroMCP-Java#106]
It happens after building with eclipse
When loading .jar in multimc, minecraft is unable to load font
I unzipped .jar file, but font is still there

**Comment by Nyvyme** [comment]
![2024-01-18-12:05:57-screenshot](https://github.com/MCPHackers/RetroMCP-Java/assets/66077431/03a22bf6-aa4c-4c37-8e10-d920f9f13454)
![2024-01-18-12:06:02-screenshot](https://github.com/MCPHackers/RetroMCP-Java/assets/66077431/4bf7106c-c5d0-43ee-b1a0-070060ed6c26)
![2024-01-18-12:06:10-screenshot](https://github.com/MCPHackers/RetroMCP-Java/assets/66077431/326097b3-1a6e-4839-9486-668bdf45a7a6)
![2024-01-18-12:06:20-screenshot](https://github.com/MCPHackers/RetroMCP-Java/assets/66077431/b148a703-c2b6-4c7f-917e-ba5616484399)

**Comment by Nyvyme** [comment]
Multimc outputs this:
***
Failed to add READ_ME_I_AM_VERY_IMPORTANT
Failed to add pack.mcmeta
***

**Comment by forkiesassds** [comment]
Did you forget to put in font.txt?

**Comment by Nyvyme** [comment]
> Did you forget to put in font.txt?

Yes, that was the problem
Thx for your answer
