### ISSUE TITLE
java cant find main class

### ISSUE THREAD

**Issue by radmanplays** [MCPHackers/RetroMCP-Java#111]
when i try to open the jar file for retromcp it dosnt open and even when i try to open it with cmd it says "could not find main class" heres the full log :

```
C:\Users\HOME\Downloads\retro>java -version
java version "1.8.0_391"
Java(TM) SE Runtime Environment (build 1.8.0_391-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.391-b13, mixed mode)

C:\Users\HOME\Downloads\retro>java RetroMCP-Java-GUI.jar
Error: Could not find or load main class RetroMCP-Java-GUI.jar
```

**Comment by PhoenixVX** [comment]
You are not opening it properly. You need to use -jar for it to auto detect the main class. `java -jar RetroMCP-Java-GUI.jar`
