### ISSUE TITLE
1 question.

### ISSUE THREAD

**Issue by bruh2899** [MCPHackers/RetroMCP-Java#115]
How do I make a workspace, I am trying to do what I do using the old MCP but it doesn't work like that. Can someone help
(sorry for posting another question only 45-60 minutes after my other issue)

**Comment by PhoenixVX** [comment]
Please use the Discussions tab for issues unrelated to RetroMCP.

If you're using v1.0, create a workspace folder in the same directory as the RetroMCP JAR is in and then import the minecraft and minecraft_server folders as projects (Import existing projects from source).

If you're using v1.0-pre3, open the workspace folder as an Eclipse workspace or open the projects individually for Intellij support.
