### ISSUE TITLE
where are the textures

### ISSUE THREAD

**Issue by FlashlightET** [MCPHackers/RetroMCP-Java#12]
i cant find the textures referenced in the code on my computer at all aside from actual minecraft installations

**Comment by FlashlightET** [comment]
I think it might just be the minecraft.jar in lib\client?

**Comment by FlashlightET** [comment]
i must be correct but i might be wrong too

**Comment by Lassebq** [comment]
If you're just looking for vanilla assets you can look at the minecraft.jar in `jars`.
It has everything from before decompiling. Resources, assets, textures, classes - everything. I hope this solves your issue.

**Comment by FlashlightET** [comment]
i just edited the files inside lib/client/minecraft.jar and its working for custom resources. i already added one multi-sided block and this is pretty easy

**Comment by Lassebq** [comment]
This is not the intended way to edit assets, they won't be included in the final build.
Please do it as it says [here](https://github.com/MCPHackers/RetroMCP-Java/wiki/Working-with-source) next time

**Comment by FlashlightET** [comment]
oh ok, thanks. (i never worked with java before so this is just a n00b mistake)
