### ISSUE TITLE
Creating alpha 1.0.1_01 patch does not work

### ISSUE THREAD

**Issue by Melthen-bor** [MCPHackers/RetroMCP-Java#121]
It does not generate a patch even though I clicked the create patch button. It just states that the task was successful but there are no patches generated.

**Comment by PhoenixVX** [comment]
You need to provide more info than that. Patches are only created when there is a difference in the source code from what was decompiled. If you're looking to build a mod, use the build task instead.

**Comment by Melthen-bor** [comment]
I modified the source code and it did not generate a patch

**Comment by PhoenixVX** [comment]
I can confirm that this does work in both v1.0-pre3 and v1.0. Are you sure you are modifying the right source code? The `source` folder in v1.0 is not the source folder that should be edited. You should be editing the `src` folder if you are not.

**Comment by Melthen-bor** [comment]
I was modifying both sorry for wasting your time.
