### ISSUE TITLE
support ANSI escape codes in System.out output

### ISSUE THREAD

**Issue by P250** [MCPHackers/RetroMCP-Java#124]
Pretty self-explanatory. I want to be able to write `System.out.println(\u001B[1;31m HELLO);` to get a bright red text in the Output console window. 

I also wanted to be able to change the size of the font in the Output window by holding Ctrl and +/-. 

The final feature I wanted to add was the Output window in the GUI always scrolling to the bottom when new text is appended.

Is this something you'd be interested in ?

**Comment by P250** [comment]
![image](https://github.com/MCPHackers/RetroMCP-Java/assets/25860964/4c98150c-3565-4068-8911-ddcc27700d78) 

I was struggling to read console output before, so it's nicer now!

**Comment by P250** [comment]
Ah, sorry for not making this clear, but the reason I wanted these changes is because I was really struggling to read console output from when I modified the decompiled code to print statements. Being able to change the font, size, and even add colour, would be really helpful for debugging!

**Comment by PhoenixVX** [comment]
You should make a PR instead of asking "If this is something we want".

**Comment by P250** [comment]
Okay
