### ISSUE TITLE
Reorganizing Code in b1.7.3 Issue

### ISSUE THREAD

**Issue by lowercasebtw** [MCPHackers/RetroMCP-Java#131]
I wanted to clean up the file structure and move some stuff around in the beta 1.7.3 source code, and yes I went through and imported everything and changed everything necessary yet I am getting these issues:

![image](https://github.com/MCPHackers/RetroMCP-Java/assets/126462578/1b85ab60-91d6-4b35-ba2f-f996ab0e90fa)

The thing is though, the files its refering to in the src directory don't exist anymore as I moved them, and I have infact imported the proper location of these files in the required classes but it seems to be ignoring the new path/import.

How can I fix this?

**Comment by lowercasebtw** [comment]
incompatible types: a cannot be converted to b

b does not exist

a does

**Comment by PhoenixVX** [comment]
Does this only happen in RMCP?

**Comment by lowercasebtw** [comment]
I don't know any other mcp related thing for beta 1.7.3 besides this so idk.

**Comment by lowercasebtw** [comment]
Is there a discord I can join?

**Comment by lowercasebtw** [comment]
I fixed it by downgrading to pre-3 for IntelliJ support and IntelliJ showed me all the issues that the log output didn't/wouldnt.

The thing is though, it was importing from the "src" path directly from the Minecraft jar according to IntelliJ, when it shouldn't. That's why the log output didn't show me the real errors, I had to go through and manually import the right files in the code because it was trying to import the wrong file automatically.

**Comment by lowercasebtw** [comment]
e

**Comment by PhoenixVX** [comment]
> Is there a discord I can join?

RetroMCP-Java's home can be found on [Modification Station](https://discord.gg/8Qky5XY), which is a modding server for legacy Minecraft.

As for the issue itself, this is most likely a v1.0 issue since it doesn't affect v1.0-pre3. v1.0 changed a lot of things and was originally intended to be another pre-release, but that did not happen.

**Comment by PhoenixVX** [comment]
Closing this issue as inactive.
