### ISSUE TITLE
Edit an already existing mod ?

### ISSUE THREAD

**Issue by spychopat** [MCPHackers/RetroMCP-Java#136]
Maybe it's not the best place to ask for help, but i can't figure where else i could ask.
I'm trying to edit already existing mods for Minecraft b173

What i do :
- i setup RetroMCP for version b173
- i edit the minecraft.jar to add the mod i want to edit (optifine in this case)
- i press "decompile" ----> errors

The source seem to decompile correctly, because i can find all the java files in src, but i still get some errors.
If i try to recompile or even just run the client, it's not going to work.
Here what i get after decompiling : 
![image](https://github.com/MCPHackers/RetroMCP-Java/assets/16687705/8dee249e-4b3b-4fab-8449-d5f3bc40709c)

I've also tried to edit another mod before, and had similar issue.
Maybe i need a specific version of java ? I use Zulu 8
Thanks to anyone who could help me !
(rn, i'm just trying to remove fog rendering on optifine, but i could use the knowledge to edit other mods)

**Comment by PhoenixVX** [comment]
Decompilation will not always produce recompilable source code.

In this case, you will need to modify the source code to be able to recompile (ideally without changing functionality), update your reobfuscation hashes, then add your changes on top of that.

In the case of the first error though, you can fix that by enabling the option "Strip generics" then re-decompiling.
As for the latter issues, that appears to be an issue with an unmapped method in TextureHDFX subclasses.

**Comment by spychopat** [comment]
Hey thanks !
I'll try to do this, but it seems like it can be a lot of work ahah, I'm not expert xD
At least I know where to begin now

**Comment by PhoenixVX** [comment]
Closing this issue as resolved.

Please use the discussions tab if you wish to comment again.
