### ISSUE TITLE
CLI version can't decompile merged nor apply patches from merged.patch

### ISSUE THREAD

**Issue by SolsticeSpectrum** [MCPHackers/RetroMCP-Java#137]
The CLI version should have an option to decompile and patch merged.
Maybe by doing `decompile merged` which would automatically set side to MERGED
Currently it will just always set side to ALL in the config whenever you do any type of action

Why is this useful?
Let's say I want to have easy to use repository with my mod, I could put a script in place which will
setup the environment for you as long as the CLI version allows me to do so

Currently you can only operate in ALL mode

**Comment by PhoenixVX** [comment]
The CLI version can do this with using -side=merged.

The help command exists and tells you how to use a command. Running `help decompile` will for example return
```
Optional parameters:
-side: ANY, CLIENT, SERVER, MERGED
```
ANY is ALL as a sidenote

As an aside, it seems like earlier versions have issue with setting side with this method so if you're having issues, try updating.
