### ISSUE TITLE
Ability to convert merged source folder to client/server

### ISSUE THREAD

**Issue by SolsticeSpectrum** [MCPHackers/RetroMCP-Java#138]
This would be useful if you suddenly change your mind and want to split these two

**Comment by PhoenixVX** [comment]
I don't believe this is necessary in RetroMCP itself. You can however make a plugin using the following as a base:
https://github.com/MCPHackers/RetroMCP-Java/tree/main/src/test/java/org/mcphackers/mcp

It should be pretty simple to read in the mappings, then split based on if the class has client/server side names. If it has both or does not exist, then you copy it to both sides.
