### ISSUE TITLE
RetroMCP-Java-CLI.jar stopped working

### ISSUE THREAD

**Issue by Nyvyme** [MCPHackers/RetroMCP-Java#141]
Today I tried to recompile my mod and I noticed that `RetroMCP-Java-CLI.jar` just stopped working.

It halts after displaying `RetroMCP v1.0.1`.

```
$ java -jar RetroMCP-Java-CLI.jar recompile client
Changing language to to en_US
Changing language to to en_US
RetroMCP v1.0.1
```

My java version: `1.8.0_412 Zulu 8.78.0.19-CA-linux64`

UPD: I think this is something with your website. Because I can't open it through "mcphackers.org" or "mcphackers.github.io".

**Comment by PhoenixVX** [comment]
Looks to be an issue on your end. It is working fine on my side, not to mention the fact that the website is hosted through GitHub Pages so the website shouldn't be going down unless GitHub Pages goes down (which is unlikely).

I've tried with the latest commit #[d079ca1](https://github.com/MCPHackers/RetroMCP-Java/commit/d079ca1ef34a21640959e20bf2061125974a9225 and running with and without the `recompile client` command is working fine.

**Comment by Nyvyme** [comment]
I tried to open website with VPN, but still nothing.
My github pages work correctly.
`RetroMCP-Java-CLI.jar` still halts after `RetroMCP v1.0.1` message.
I'll try other router.

**Comment by Nyvyme** [comment]
Yeah, issue with my new router.
I'll try something but is there a way to disable update checks or something that `.jar` is trying to do?

**Comment by PhoenixVX** [comment]
Since it looks like you built this from source, you can just comment out the checks. Otherwise, there isn't a built in method to do it. 

Something to consider for the future, it seems.

**Comment by Nyvyme** [comment]
Ok, I'll disable it in my fork.

**Comment by Nyvyme** [comment]
Now website and `.jar` works. I don't know what with my router caused this issue, but now it's completely solved.
