### ISSUE TITLE
The working path is not consistent on Linux

### ISSUE THREAD

**Issue by vlOd2** [MCPHackers/RetroMCP-Java#24]
The working path is not consistent on Linux.

Example:
If you run it from a file browser (using double-click) the working path is set to your home directory
Which might cause data loss.

The working path should be in the directory that the jar file was ran in.

**Comment by Lassebq** [comment]
Sorry, but I think my final decision on this issue is that it's related to the file manager, not the tool. Don't worry though, I'll be sure to include separate releases for CLI and GUI so you could launch either with terminal, with a consistent working directory.
