### ISSUE TITLE
custom versions/unlisted versions

### ISSUE THREAD

**Issue by SprainedSpark89** [MCPHackers/RetroMCP-Java#30]
could you add a way to make mods and versions like b1.8 pre decompile?
it could help people who make mods

**Comment by Geolykt** [comment]
It is planned to re-add the versions list, which would make older versions usable again.
But what exactly do you mean with pre-decompile?

**Comment by PhoenixVX** [comment]
They likely mean b1.8-pre version. As for that, we are currently working more-so on RMCP itself than working on porting (shitty) mappings to other versions. If you wish to help contribute, I'd suggest completing the b1.8 mappings, and then we can use Matcher to port the mappings to b1.8-pre automatically.

**Comment by PhoenixVX** [comment]
Closing as this is unrelated to RMCP itself (related to mappings), and because of inactivity.

**Comment by SprainedSpark89** [comment]
i also meant like versions that are modded like olddays revisited i wanted to try adding noise generators that were not in the mod but remcp had an error because there was a class or 2 that is not in the version it was based on
