### ISSUE TITLE
Compiling RetroMCP

### ISSUE THREAD

**Issue by DisBot404** [MCPHackers/RetroMCP-Java#34]
I noticed that RMCP has been updated what seems like alot, so i decided to try and compile it. There doesnt seem to be a easy way to get the combined jar (RetroMCP-Java-All). Ive tried for a while and tried to find documentation, theres none. How do you do it?

**Comment by Blizzardfur-Maxxx** [comment]
none of the new commits  work yet due to incompatible mappings

**Comment by DisBot404** [comment]
Alright, but is there any way to compile anyway?

**Comment by Lassebq** [comment]
Yes, it uses gradle, a common build system for java. The build script was modified to create -GUI and -CLI jars after a certain commit, the only difference from -all jar is the main class.
