### ISSUE TITLE
Don't try to download natives on FreeBSD

### ISSUE THREAD

**Issue by glowiak** [MCPHackers/RetroMCP-Java#37]
because it breaks and we have our runtimes to run mc anyway.

Is the native download the last step that needs to be done?

**Comment by PhoenixVX** [comment]
Is there a centralized place for FreeBSD natives? Rather than not downloading natives, we can implement support for them. If in the case that there is no centralized place, we can always just make it print out a notification telling the user to fill in the natives themselves.

**Comment by PhoenixVX** [comment]
Closing as this is inactive.

**Comment by glowiak** [comment]
@PhoenixVX I host one library here https://codeberg.org/glowiak/lwjgl-libs/src/branch/master/x86_64/2

Anyway I manually inserted the file into right place and now it works fine.
And I was not inactive, thou respondest a month after this got opened, sir.

**Comment by PhoenixVX** [comment]
What about the other natives? JInput, OpenAL... etc?

**Comment by glowiak** [comment]
@PhoenixVX These are not jarfiles. These need to be placed in the natives directory. Normal libs work with them.
