### ISSUE TITLE
How does recompile work?

### ISSUE THREAD

**Issue by Cubeking33** [MCPHackers/RetroMCP-Java#38]
Everytime is try to use it it just boots up regular minecraft with no changes

**Comment by PhoenixVX** [comment]
Recompile is used to recompile your code, mainly for reobfuscation. While you can run these modified classes with the start client/server task, it is more recommended to use an IDE for running and debugging your mod, such as Intellij IDEA or Eclipse.

**Comment by Cubeking33** [comment]
Ok, so I tried using eclipse to export it as a jar and it just crashes when I try to launch it

**Comment by PhoenixVX** [comment]
Is there a log? Error message please?

**Comment by PhoenixVX** [comment]
Oh wait, don't use Eclipse to export it as a JAR.

**Comment by Cubeking33** [comment]
How do i do it then?

**Comment by PhoenixVX** [comment]
Recompile, reobfuscate, zip up the contents of the reobf/minecraft or reobf/minecraft_server folders. Add those files to your Minecraft.JAR to apply your mod.

**Comment by Cubeking33** [comment]
Ok one minute

**Comment by Cubeking33** [comment]
So I zipped up the files then how do I add it to the JAR?

**Comment by PhoenixVX** [comment]
Extract the files into a JAR.

**Comment by Cubeking33** [comment]
so turn the zip into a jar

**Comment by PhoenixVX** [comment]
Not really, but sure?

**Comment by Cubeking33** [comment]
O K ill try it ig

**Comment by Cubeking33** [comment]
was I supposed to turn the reob/minecraft.zip into a jar?

**Comment by PhoenixVX** [comment]
no. You're supposed to put the contents of that zip file into your Minecraft.JAR and delete META-INF like any other old mod does.

**Comment by Cubeking33** [comment]
ohhhhhhhh

**Comment by Cubeking33** [comment]
nah it still didnt work let me retry decompiling and redo the other stuff

**Comment by Cubeking33** [comment]
It still doesn't work it only is working in eclipse

**Comment by PhoenixVX** [comment]
Decompile, edit, recompile, reobfuscate, grab files from reobf/minecraft, put them in Minecraft.JAR, delete META-INF. 

Make sure this isn't done in the vanilla launcher or your mod will be deleted. You can remove the SHA hash in the version JSON though to get around that.

**Comment by Cubeking33** [comment]
Wait, no vanilla launcher?

**Comment by Cubeking33** [comment]
I swear that used to work

**Comment by PhoenixVX** [comment]
Vanilla launcher checks SHA hash, you'll have to fix the version JSON to not have a SHA hash that way it won't be re-downloaded since the SHA hash won't match since the JAR is modified. Realistically, for modding, you shouldn't even be using the vanilla launcher, but rather MultiMC or Prism instead, or really anything else.

**Comment by AnnoyedUser420** [comment]
Alright what's the ruckus

**Comment by Cubeking33** [comment]
Uhhhhh, nothing. Anyways whenever I have tried to use multimc it doesnt load and says an error

**Comment by PhoenixVX** [comment]
Okay, what's that error

**Comment by Cubeking33** [comment]
archive does not recognize a modpack type

**Comment by AnnoyedUser420** [comment]
Why are you trying to do it as a modpack

**Comment by Cubeking33** [comment]
I am nicht

**Comment by PhoenixVX** [comment]
Open the instance settings, click "Add to Minecraft.JAR", select the zip file.

**Comment by Cubeking33** [comment]
Where is that???

**Comment by PhoenixVX** [comment]
Right bar, edit instance, right bar, Add to Minecraft.jAR

**Comment by Cubeking33** [comment]
there is no add to minecraft.jar

**Comment by PhoenixVX** [comment]
![image](https://user-images.githubusercontent.com/24632178/209581401-bd13bc30-0977-4717-a2cd-b17c0b707eea.png)

**Comment by PhoenixVX** [comment]
Add to Minecraft.JAR on the right bar.

**Comment by Cubeking33** [comment]
yeah i feel stupid i found it right after i said that

**Comment by AnnoyedUser420** [comment]
It's okay, we're all blind every once in a while

**Comment by AnnoyedUser420** [comment]
Does it work now?

**Comment by Cubeking33** [comment]
Yes it works now I'm gonna close this
