### ISSUE TITLE
Alpha 1.0.15 has the wrong server version mapped to it

### ISSUE THREAD

**Issue by pearkid** [MCPHackers/RetroMCP-Java#43]
Alpha 1.0.15 maps to server a0.1.2_01.jar instead of a0.1.0.jar

**Comment by PhoenixVX** [comment]
This is an issue for [BetterJSONs](https://github.com/MCPHackers/BetterJSONs) for V2 version format (supported by RMCP v1.0) and an issue for [MCPHackers.github.io](https://github.com/MCPHackers/MCPHackers.github.io) for V1 version format.

Closing as this issue is in the wrong repository.
