### ISSUE TITLE
c0.0.11a fails to decompile (RetroMCP-Java-GUI.jar, ver. 1.0)

### ISSUE THREAD

**Issue by EGAMatsu** [MCPHackers/RetroMCP-Java#45]
Error on line 17 in minecraft\src\com\mojang\minecraft\level\DirtyChunkSorter.java
name clash: compare(com.mojang.minecraft.level.Chunk,com.mojang.minecraft.level.Chunk) in com.mojang.minecraft.level.DirtyChunkSorter overrides a method whose erasure is the same as another method, yet neither overrides the other
  first method:  compare(java.lang.Object,java.lang.Object) in com.mojang.minecraft.level.DirtyChunkSorter
  second method: compare(T,T) in java.util.Comparator

Error on line 31 in minecraft\src\com\mojang\minecraft\level\DirtyChunkSorter.java
name clash: compare(java.lang.Object,java.lang.Object) in com.mojang.minecraft.level.DirtyChunkSorter and compare(T,T) in java.util.Comparator have the same erasure, yet neither overrides the other

**Comment by PhoenixVX** [comment]
Use strip generics option.

**Comment by EGAMatsu** [comment]
How do I generate a workspace?

**Comment by PhoenixVX** [comment]
If you're using Eclipse, make a workspace folder in the project folder, then import the minecraft folder.

**Comment by PhoenixVX** [comment]
Closing this issue.
