### ISSUE TITLE
Error when decompiling Classic 0.0.11a

### ISSUE THREAD

**Issue by xX420MCplayerXx** [MCPHackers/RetroMCP-Java#48]
Hello. I am experiencing a persistant error with RetroMCP v1.0. Whenever I try to decompile Classic 0.0.11a, it Finishes with errors. The errors being:
"Error on line 17 in minecraft\src\com\mojang\minecraft\level\DirtyChunkSorter.java
name clash: class DirtyChunkSorter has two methods with the same erasure, yet neither overrides the other
  first method:  compare(com.mojang.minecraft.level.Chunk,com.mojang.minecraft.level.Chunk) in java.util.Comparator
  second method: compare(java.lang.Object,java.lang.Object) in com.mojang.minecraft.level.DirtyChunkSorter

Error on line 31 in minecraft\src\com\mojang\minecraft\level\DirtyChunkSorter.java
name clash: compare(java.lang.Object,java.lang.Object) in com.mojang.minecraft.level.DirtyChunkSorter and compare(com.mojang.minecraft.level.Chunk,com.mojang.minecraft.level.Chunk) in java.util.Comparator have the same erasure, yet neither overrides the other"
I have no clue on how to fix this.

**Comment by PhoenixVX** [comment]
Use "Strip generics" option.

**Comment by xX420MCplayerXx** [comment]
It worked! Thank you!
