### ISSUE TITLE
IntelliJ support is broken (or non-existent) + broken jar locations when importing from Eclipse 

### ISSUE THREAD

**Issue by forkiesassds** [MCPHackers/RetroMCP-Java#52]

**Comment by mudkipdev** [comment]
Don't combine two issues into one, this makes tracking harder. Also IntelliJ support is missing temporarily in an attempt to release v1.0 faster.

**Comment by PhoenixVX** [comment]
Intellij support is in latest. The Eclipse project is definitely not broken. How are you importing?

**Comment by forkiesassds** [comment]
> Intellij support is in latest. The Eclipse project is definitely not broken. How are you importing?

File -> New -> Module from Existing Sources

**Comment by P3NG00** [comment]
Can confirm. Normally use intellij. Have been forced to use eclipse and import the 'client' and 'server' into a workspace i had to create.

**Comment by PhoenixVX** [comment]
Don't use that. For Intellij support, use latest commits. Also, the way you said Eclipse locations were broken was completely different.

**Comment by PhoenixVX** [comment]
> Can confirm. Normally use intellij. Have been forced to use eclipse and import the 'client' and 'server' into a workspace i had to create.

That is the intended way from now on. Closing this issue as both issues have been resolved.
