### ISSUE TITLE
High CPU usage for a1.2.6

### ISSUE THREAD

**Issue by SpiderTwink** [MCPHackers/RetroMCP-Java#57]
I don't know if it's just alpha 1.2.6, or my computer, but when running Alpha 1.2.6 through RetroMCP for testing, compared to a session of a1.2.6 (unmodified) running via BetaCraft, not only is RetroMCP's session have a more unstable CPU usage, but is also using about 40-50% more CPU usage than the BetaCraft session (30-low 50% CPU for BetaCraft, 60-high 90% for RetroMCP using the same settings), making for testing with 2 sessions under RetroMCP unusable due to my laptop lagging a ton.

**Comment by PhoenixVX** [comment]
If you have an Intel GPU, you can try using 3D acceleration by adding `-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump` to your JVM arguments.

Otherwise, I can't really think of anything else that would massively affect performance.

**Comment by PhoenixVX** [comment]
Is this still an issue?

**Comment by SpiderTwink** [comment]
i havent tried it yet, been busy as of late so i havent been reading my
emails too much

**Comment by PhoenixVX** [comment]
Closing issue as inactive.

Please reopen this issue if the issue persists and is reproducible.
