### ISSUE TITLE
Import project into Eclipse

### ISSUE THREAD

**Issue by sterh1275** [MCPHackers/RetroMCP-Java#60]
I decided to upgrade from version 1.0-pre3 to 1.0. And I'm having a problem importing into Eclipse. On I opened the folder "workspace" in Eclipse and the project was imported. In 1.0 opening a folder "minecraft" does nothing. What am I doing wrong? I am sorry for my English.

**Comment by Lassebq** [comment]
Again, 1.0 doesn't use workspace folder anymore, you make one youself.
It's done for the purpose of having your own workspace with preferred settings
And migrating projects from prereleases to v1.0 is not supported, due to project structure change

**Comment by Lassebq** [comment]
If you want to open projects in the new version, you need to make a workspaces first and then go to Import -> Import existing project, and from there specify path to minecraft/minecraft_server folder

**Comment by sterh1275** [comment]
Thanks!
