### ISSUE TITLE
Custom Java compiler selection

### ISSUE THREAD

**Issue by glowiak** [MCPHackers/RetroMCP-Java#64]
Basically I would like to compile my mod for Java 6 instead of 8.

Is there a way to change the used compiler?

**Comment by counter185** [comment]
You can try `Options` > `Recompile` > `Set JAVA_HOME used for compiling`
![obraz](https://github.com/MCPHackers/RetroMCP-Java/assets/33550839/2c5342f3-6877-4142-821a-bbc048b83dfb)
