### ISSUE TITLE
alpha 1.0.16 Recompile finishes with errors

### ISSUE THREAD

**Issue by GalaxyModzYT** [MCPHackers/RetroMCP-Java#66]
I tried recompiling a1.0.16 after changing the version string, and it says that it completed with errors:

PATH_TO_RetroMCP\a1.0.16\minecraft\src\net\minecraft\src\NetClientHandler.java
unreported exception java.io.IOException; must be caught or declared to be thrown

and the game doesn't recompile, anyone know how to fix this?

**Comment by PhoenixVX** [comment]
Fix the issue then update reobfuscation hashes.

If you are attempting to mod the Lilypad arg, use Alpha a1.1.0 instead as that's the real version Lilypad is developed on.
