### ISSUE TITLE
Can i just fetch the JARs without installing?

### ISSUE THREAD

**Issue by goog00goog** [MCPHackers/RetroMCP-Java#73]
I just want the jars

**Comment by PhoenixVX** [comment]
??

Download them from the Minecraft Fandom, BetaCraft servers, or from Omniarchive.

Not sure why this issue is here.

**Comment by mudkipdev** [comment]
Hello, you can download the version jars and mappings at MCPHackers' website:
https://mcphackers.org/versions.html
