### ISSUE TITLE
how to edit alpha splash text/version text/HUD?

### ISSUE THREAD

**Issue by goog00goog** [MCPHackers/RetroMCP-Java#76]
title

**Comment by PhoenixVX** [comment]
Same as any other version. Splashes would be in GuiMainMenu or in splashes.txt (which doesn't exist until later), so it's the latter. Version text is set in Minecraft.java and HUD text is set in GuiIngame.java.

Closing as this doesn't relate to RMCP itself. You should join the Modification Station Discord if you want to get more dedicated help as this is not the place for this.
