### ISSUE TITLE
build task creates an empty zip file

### ISSUE THREAD

**Issue by Niterux** [MCPHackers/RetroMCP-Java#79]
![image](https://github.com/MCPHackers/RetroMCP-Java/assets/110568869/f73c054c-dc45-4650-b6a2-aaa7780dbb98)
![image](https://github.com/MCPHackers/RetroMCP-Java/assets/110568869/beff9c52-6a32-4d7a-b8cb-a622f7ffc9c0)
![image](https://github.com/MCPHackers/RetroMCP-Java/assets/110568869/6b224017-1482-4251-893f-48195decfa97)

**Comment by PhoenixVX** [comment]
Have you edited anything? Build creates a reobfuscated ZIP of modified classes.

**Comment by Niterux** [comment]
I decompiled a mod and then fixed the source until it worked and then builded

**Comment by PhoenixVX** [comment]
Then that's why. updatemd5hashes is used to fix reobfuscation hashes in the case of a failed decompilation. Now that the mod is decompiled correctly and you've run updatemd5, you can mod the mod or MC and then you can apply the mod separately without having to ship a modified version of the mod (in case of an API/library or in case you didn't edit the mod itself).

**Comment by Niterux** [comment]
How do I get the full modified version of the mod that I can apply on top of base mc?

**Comment by PhoenixVX** [comment]
You can use the full build option in settings then rebuild. I don't recommend this for making mods but if it's just for yourself, then you can use it.

**Comment by Niterux** [comment]
I am using the CLI, what do I do in CLI?

**Comment by PhoenixVX** [comment]
I believe... `--build=fullbuild` might work? So something like `build --build=fullbuild`. Nothing else, edit the settings file or open up the GUI to edit settings.

**Comment by Niterux** [comment]
it says unrecognized
PS C:\Users\parke\Downloads\retromcp> java -jar "RetroMCP-Java-CLI.jar" build --build=fullbuild
RetroMCP v1.0
Unrecognized option: -build
 Client  100% [==========] Finished!
 Server  100% [==========] Finished!
[INFO]: Finished successfully!
where is the settings file?

**Comment by Lassebq** [comment]
parser flags use single `-`

**Comment by Niterux** [comment]
tried with single -, same error

**Comment by Lassebq** [comment]
use `help build` the flag is a simple boolean value -fullbuild=true

**Comment by Niterux** [comment]
ah, I didn't know help [task] was a thing! the program or wiki doesn't explain that i think ._.

**Comment by PhoenixVX** [comment]
Mostly because this changed a lot in between pre-releases and is too little used to deserve a page in the wiki. 

Anyways, seems like this issue is closable, correct?

**Comment by Niterux** [comment]
It seems to have spat out a minecraft jar without my changes :/

**Comment by PhoenixVX** [comment]
???

Can you show your modified classes and the modified JAR?

**Comment by Niterux** [comment]
I am so confused I am sorry there is such little instructions that I have no idea what I am doing
I didnt modify any jars or classes only the source files that the decompilation process spat out
start client appears to show the changes that I made but taking the minecraft.jar in the "build" folder seems to have everything before my modifications

**Comment by Niterux** [comment]
basically i removed discordthread.java and all of the files and code associated with it in the source, discordthread.java sends a log message saying "Starting Discord RPC thread.", this log message doesn't appear when I use the start client task after my changes, but in the fullbuild it appears in the logs and inside of the minecraft.jar file in the build folder there is a discordthread.class file

**Comment by PhoenixVX** [comment]
Ah yes... full build will bundle all classes from the original Minecraft JAR and all modified classes. This should still work as you are no longer calling the class, it is just present in the JAR. Try testing the JAR first.

**Comment by Niterux** [comment]
I tested out the jar and it says "Starting Discord RPC thread." in prism launcher

**Comment by Niterux** [comment]
really weird, i extracted the jar and checked the class files using a program called dirtyJOE that my friend told me about and it still contains the references to the discord code that I removed :/

**Comment by Niterux** [comment]
sorry for being so annoying and dumb i dont understand anything

**Comment by PhoenixVX** [comment]
Is this still an issue?

**Comment by Niterux** [comment]
i deleted the project and gave up so ig it's technically still an issue just not for me xd

**Comment by PhoenixVX** [comment]
Closing issue as inactive. Please re-open if the issue occurs again.
