### ISSUE TITLE
can't select minecraft classic 0.24 to 0.30

### ISSUE THREAD

**Issue by Rainb0wSkeppy** [MCPHackers/RetroMCP-Java#8]
![image](https://user-images.githubusercontent.com/48686725/169883648-74e6965b-78ac-48ad-88ee-cceb9351e22f.png)
where is minecraft 0.30

**Comment by Lassebq** [comment]
The list of versions only contains versions which have been mapped and patched to be properly decompiled. If a version isn't present in this list it means it's not mapped. We are still developing mappings for other versions. Stay patient.
