### ISSUE TITLE
org.lwjgl.LWJGLException: Pixel format not accelerated

### ISSUE THREAD

**Issue by goog00goog** [MCPHackers/RetroMCP-Java#80]
im on windows 7 ultimate with zulu azul jdk

**Comment by Lassebq** [comment]
Can you run regular Minecraft in the first place?

**Comment by PhoenixVX** [comment]
Only thing I can think of in this case would be bad natives but these natives work for everyone on Betacraft so...

**Comment by goog00goog** [comment]
idk
i have a generic video card anyway

**Comment by PhoenixVX** [comment]
Can you run MC in the first place? What about from Betacraft?

**Comment by goog00goog** [comment]
i think it has to do with drivers but idk what drivers to get for this generic looking driver

**Comment by goog00goog** [comment]
doesnt even show up in dev mgmt

**Comment by PhoenixVX** [comment]
Open up Task Manager, go to the hardware section, look at GPU.

**Comment by goog00goog** [comment]
i have no gpu :skull:

**Comment by PhoenixVX** [comment]
Then you probably have an APU. Do you have an AMD processor (CPU)?

**Comment by goog00goog** [comment]
i have an i3-2100

**Comment by PhoenixVX** [comment]
wtf

**Comment by goog00goog** [comment]
its too much work to replace it
special screws

**Comment by PhoenixVX** [comment]
Can you see the brand on the GPU itself?

**Comment by goog00goog** [comment]
wait...
gigabyte gv-r724oc-2gi

**Comment by PhoenixVX** [comment]
Try installing these: https://www.gigabyte.com/Graphics-Card/GV-R724OC-2GI-rev-20-21/support#support-dl-driver

**Comment by SolDev69** [comment]
> i have an i3-2100

Yo you have my old cpu. I used to run minecraft on one of those for years. You need specific graphics drivers.

**Comment by goog00goog** [comment]
got them installed  and now it works + aero!!!
thx everybody
