### ISSUE TITLE
[Feature Suggestion] Clear Console Output

### ISSUE THREAD

**Issue by JustJory** [MCPHackers/RetroMCP-Java#86]
For the GUI version of RetroMCP-Java I think there should be a simple button that clears the console output, the reason why I am suggesting this feature is its confusing to see which error is from the previous attempt at recompiling or the current attempt. Here is a concept image I made in Paint.net of what it could look like. ![image](https://cdn.discordapp.com/attachments/1105943511393636424/1148294514541338764/image.png)
However let me know if this already exists and I didn't see it in the options or if this is a bad idea or the buttons should be somewhere else like in a drop down menu.

**Comment by JustJory** [comment]
Sorry I don't know how to add labels, I don't use github very often lol.

**Comment by PhoenixVX** [comment]
I would instead add it as a right click context menu but yeah, I'll try and get it working when I'm not working lmao.

**Comment by JustJory** [comment]
> I would instead add it as a right click context menu but yeah, I'll try and get it working when I'm not working lmao.

Alright thank you I really appreciate it

**Comment by PhoenixVX** [comment]
Implemented in https://github.com/MCPHackers/RetroMCP-Java/commit/8113849dd21250d8adf0e6b8e1d2ab06d12cf558

Closing issue as feature has been implemented.
Thank you, have a nice day!
