### ISSUE TITLE
Eclipse: Impossible to rename project

### ISSUE THREAD

**Issue by kangarko** [MCPHackers/RetroMCP-Java#88]
When trying to import Alpha and Beta clients into Eclipse I need to distinguish between the two to port some features.

Unfortunately renaming them gives me this problem:

![a](https://i.imgur.com/etAhc8c.png)

I don't know if this is a RetroMCP bug or I am doing something wrong. Perhaps you could automatically append the version of the client and server for user convenience, because a lot of people are having multiple versions opened to port features and or patches.

Here is my dir structure:
![a](https://i.imgur.com/DRTixHm.png)

Thanks.

**Comment by PhoenixVX** [comment]
This is not a RetroMCP issue. This is an Eclipse issue. The base project name should be `Minecraft Client`, `Minecraft Server`, and `Minecraft Merged` (for merged codebases).

**Comment by kangarko** [comment]
Thanks, got'cha. How about my suggestion to implicitly append version to Eclipse project files? Would guess many people work with multiple versions at the same time.

**Comment by PhoenixVX** [comment]
Newer RMCP-Java versions do not come with a workspace and make the user configure the workspace themselves. Essentially, it's unnecessary in that case. Also, have you tried to rename projects in v1.0/latest commits?

**Comment by kangarko** [comment]
Thanks. I compiled RetroMPC from source from the latest commit, imported 1.2.5 Client but upon renaming facing the exact same Eclipse rror:

![a](https://i.imgur.com/oGzN9ZH.png)

**Comment by PhoenixVX** [comment]
Closing issue as inactive and unrelated to RMCP itself.
