### ISSUE TITLE
Inf-20100616

### ISSUE THREAD

**Issue by TristanCorso911** [MCPHackers/RetroMCP-Java#92]
My inf-20100616-1 is missing for RetroMCP.

**Comment by PhoenixVX** [comment]
First off, Infdev 20100616-1 has not been put into RMCP yet.
Second off, this is the wrong repository to comment this on.
Third off, use https://github.com/MCPHackers/RetroMCP-Java/discussions if you're going to ask questions that have a simple answer.

**Comment by TristanCorso911** [comment]
how do you add a1.2.2a?

**Comment by PhoenixVX** [comment]
Stop asking for missing versions in RMCP. If you continue, you will banned from commenting on issues.

**Comment by TristanCorso911** [comment]
no
