### ISSUE TITLE
is it possible to make an unobfuscated build?

### ISSUE THREAD

**Issue by Hellscaped** [MCPHackers/RetroMCP-Java#95]
I'm trying to make a mod loader and I need to have another jar depend on the minecraft.jar

**Comment by mudkipdev** [comment]
Only the Minecraft classes are reobfuscated, classes that have been added by you will not be obfuscated

**Comment by Hellscaped** [comment]
> Only the Minecraft classes are reobfuscated, classes that have been added by you will not be obfuscated

Interesting because when I look inside build/minecraft.jar I can't find them.

**Comment by mudkipdev** [comment]
Yes, classes that you have not edited will be excluded unless you use the "full build" option (not recommended)

**Comment by PhoenixVX** [comment]
Closing issue as inactive.
